version: "3.9"
networks:
  vc-net:
    driver: bridge

services:
    test-adserver-api:
        build: .
        image: adserver-api:local
        command: npm start
        environment:
            - PORT=8080
            - API_KEY=secret-key
            - APP_DB_PSQL_URL=postgresql://eyevinn:very-secret-stuff@db:5432/session_db_dev
        ports:
            - 8080:8080
        depends_on:
            - db      
    db:
        image: postgres
        environment:
            - POSTGRES_PASSWORD=very-secret-stuff
            - POSTGRES_USER=eyevinn
            - PGDATA=/var/lib/postgresql/data/pgdata
        volumes:
            - ./.pgdata:/var/lib/postgresql/data/pgdata
            - ./migrations/psql/:/docker-entrypoint-initdb.d/
        ports:
            - 5432:5432
