version: "3.9"

services:
  test-adserver-api:
    build: .
    image: adserver-api:local
    environment:
      - PORT=8080
      - API_KEY=secret-key
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=very-secret-stuff
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes: 
      - ./.pgdata:/var/lib/postgresql/data