version: "3.9"

services:
  db:  
    image: postgres
    environment:
      - POSTGRES_PASSWORD=very-secret-stuff
      - POSTGRES_USER=eyevinn
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./.pgdata:/var/lib/postgresql/data/pgdata
      - ./migrations/psql/:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432

  test-adserver-api:
    build: .
    image: adserver-api:local
    command: npm start
    environment:
      - PORT=8080
      - API_KEY=secret-key
      - APP_DB_PSQL_URL=postgresql://eyevinn:very-secret-stuff@db:5432/session_db_test
    ports:
      - 8080:8080
    depends_on:
      - db      

  test-adserver-api-tests:
    image: adserver-api:local
    command: dockerize -wait tcp://db:5432  -wait tcp://test-adserver-api:8080 -timeout 60s bash -c "npm test"
    environment:
      - APP_URL=http://test-adserver-api:8080
      - APP_DB_PSQL_URL=postgresql://eyevinn:very-secret-stuff@db:5432/session_db_test
    depends_on:
      - db
      - test-adserver-api

